NAT_civUniforms = [
"U_I_C_Soldier_Bandit_2_F",
"U_I_C_Soldier_Bandit_5_F",
"U_I_C_Soldier_Bandit_3_F",
"TRYK_U_B_PCUGs_BLK_R",
"TRYK_U_B_PCUGs_gry_R",
"TRYK_U_B_PCUGs_OD_R",
"TRYK_shirts_DENIM_BK",
"TRYK_shirts_DENIM_BL",
"TRYK_shirts_DENIM_BWH",
"TRYK_shirts_DENIM_od",
"TRYK_shirts_DENIM_R",
"TRYK_shirts_DENIM_RED2",
"TRYK_shirts_DENIM_WH",
"TRYK_shirts_DENIM_WHB",
"TRYK_shirts_DENIM_ylb",
"TRYK_shirts_DENIM_od_Sleeve",
"TRYK_shirts_DENIM_ylb_Sleeve",
"TRYK_shirts_DENIM_BK_Sleeve",
"TRYK_shirts_DENIM_BL_Sleeve",
"TRYK_shirts_DENIM_BWH_Sleeve",
"TRYK_shirts_DENIM_R_Sleeve",
"TRYK_shirts_DENIM_RED2_Sleeve",
"TRYK_shirts_DENIM_WH_Sleeve",
"TRYK_shirts_DENIM_WHB_Sleeve",
"TRYK_U_denim_hood_3c",
"TRYK_U_denim_hood_blk",
"TRYK_U_denim_jersey_blk",
"TRYK_U_denim_jersey_blu",
"TRYK_U_B_Denim_T_BG_BK",
"TRYK_U_B_Denim_T_BG_WH",
"TRYK_U_B_Denim_T_BK",
"TRYK_U_B_Denim_T_WH"
];

NAT_civBackpacks = [
"TRYK_B_BAF_BAG_OD",
"TRYK_B_BAF_BAG_BLK",
"TRYK_B_BAF_BAG_CYT"
];
/*
"rb_antibiotic",
"rb_Waterpure",
"rb_bandage",
rb_bloodbag
"rb_Meat",
"rb_MeatC",
"rb_TacticalBacon",
"rb_BakedBeans",
"rb_TacticalBaconempty",
"rb_BakedBeansempty",
"rb_bottle",
"rb_bottleclean",
"rb_bottledirty",
"rb_bottlesalt",
rb_WoodPile
"rb_Spirit",
"rb_franta",
"rb_Spiritempty",
"rb_frantaempty",
rb_oldcan
"rb_redgull",
"rb_redgullempty",
rb_suitcase
rb_hammer
rb_saw
rb_Pallet
rb_wrench
rb_Axe
rb_Fuelcan
rb_Fuelcan_empty
rb_tire
rb_ducttape
rb_cereal
rb_RiceBox
"rb_canteen",
"rb_canteen_dirty",
rb_canteen_salt
"rb_canteen_empty",
"rb_matches",
rb_nails
"rb_knife",
rb_HandyCam
rb_Laptop
"rb_MobilePhone",
rb_SmartPhone


"rb_bandage","rb_MeatC","rb_TacticalBacon","rb_BakedBeans","rb_TacticalBaconempty","rb_BakedBeansempty","rb_knife","rb_antibiotic","rb_Waterpure","rb_canteen","rb_canteen_dirty","rb_canteen_empty"

*/